name: iqtree-pipeline

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.11
  - pandas
  - openpyxl
  - biopython
  - mafft
  - trimal
  - iqtree
  - seqkit
  - pyyaml
  - pip